FROM node:24

# Créer un dossier de travail dans le conteneur
WORKDIR /app

# Copie les fichiers (test)
# COPY files/package*.json ./
# RUN npm install
# COPY ./files/ ./

EXPOSE 3010

# Pour le push final (prod)
CMD ["npm", "run", "dev"]
# CMD ["npm", "run", "start"]
